"""empty message

Revision ID: 7a3cec62041e
Revises: 
Create Date: 2026-08-09 16:23:34.776077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7a3cec62041e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racestrokecount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swimmer_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('epreuve', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bassin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temps', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('length_index', sa.Integer(), nullable=False),
    sa.Column('dist_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stroke_count', sa.Integer(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('swimmer_key', 'date', 'epreuve', 'bassin', 'temps', 'length_index', name='uq_race_stroke_count_key')
    )
    with op.batch_alter_table('racestrokecount', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_racestrokecount_swimmer_key'), ['swimmer_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racestrokecount', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_racestrokecount_swimmer_key'))

    op.drop_table('racestrokecount')
    # ### end Alembic commands ###
