"""add race_comment table

Revision ID: ef257f40d2a0
Revises: 6bd11a91af15
Create Date: 2026-08-09 18:06:04.383067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ef257f40d2a0'
down_revision: Union[str, Sequence[str], None] = '6bd11a91af15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racecomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swimmer_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('epreuve', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bassin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temps', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('swimmer_key', 'date', 'epreuve', 'bassin', 'temps', name='uq_race_comment_key')
    )
    with op.batch_alter_table('racecomment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_racecomment_swimmer_key'), ['swimmer_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racecomment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_racecomment_swimmer_key'))

    op.drop_table('racecomment')
    # ### end Alembic commands ###
